#!/bin/bash

set -e

if [ $# -ne 2 ]; then
    echo "usage: icetray-build SRC_DIR BUILD_DIR" >&2
    exit 1
fi
SRC_DIR=$1
BUILD_DIR=$2

cd $BUILD_DIR
ROOTSYS=/usr/local/root \
PATH=$PATH:/usr/local/geant4/bin:/usr/local/cuda-12.4/bin \
cmake -S $SRC_DIR -B $BUILD_DIR -GNinja -DUSE_ROOT=ON
cmake --build $BUILD_DIR
