name: CI
on:
  push:
    branches: [ main ]
jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max